# Generated by Django 4.0.3 on 2022-03-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='has_url',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='url',
        ),
    ]
