# Generated by Django 4.0.3 on 2022-03-10 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('is_direktur', models.BooleanField(default=False)),
                ('is_dosen', models.BooleanField(default=False)),
                ('is_mahasiswa', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
